Repository gauravsinhaweb/EduSmart, pull requests merged in 2021-10, with the labels that each got.

#9 Fixed contributors page and headings
  client/public/index.html
  client/src/App.css
  client/src/pages/Chatroom.js
  client/src/pages/Classroom.js
  client/src/pages/Contributors.js
Labels: bug, enhancement, hacktoberfest-accepted, hacktoberfest

#31 Structered imports & If else to Switch & cleaned code #27
  client/src/App.js
  client/src/components/3DExplore/AnimalCellExplore.js
  client/src/components/3DExplore/Boeing777Explore.js
  client/src/components/3DExplore/TurbofanExplore.js
  client/src/components/3DExplore/index.js
  client/src/components/3DModel/AnimalCell.js
  client/src/components/3DModel/Boeing747.js
  client/src/components/3DModel/Boeing777.js
  client/src/components/3DModel/PlanetJupiter.js
  client/src/components/3DModel/PlanetMars.js
  client/src/components/3DModel/Planets.js
  client/src/components/3DModel/PlantCell.js
  client/src/components/3DModel/Skeleton.js
  client/src/components/3DModel/TurbineTurbofan.js
  client/src/components/3DModel/index.js
  client/src/components/AreoSpace.js
  client/src/components/Chatbot.js
  client/src/components/Footer.js
  client/src/components/Medical.js
  client/src/components/Navbar.js
  client/src/components/Planets.js
  client/src/components/index.js
  client/src/pages/About.js
  client/src/pages/Chat.js
  client/src/pages/ChatWindow.js
  client/src/pages/Chatroom.js
  client/src/pages/Classroom.js
  client/src/pages/Contributors.js
  client/src/pages/Home.js
  client/src/pages/Login.js
  client/src/pages/index.js
Labels: Under Review

#48 remove scroll bar for the live chat
  client/src/App.css
Labels: bug, good first issue, hacktoberfest-accepted, hacktoberfest
